# Generated by Django 6.0 on 2025-12-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_purchase_supplier_purchaseitem_purchase_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
