# Generated by Django 6.0 on 2026-01-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_location_invoicecontact_invoiceitem_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TILES', 'Tiles'), ('MARBLE', 'Marble'), ('GRANITE', 'Granite'), ('SANITARY', 'Sanitary'), ('ADHESIVE', 'Adhesive'), ('OTHER', 'Other')], default='TILES', max_length=50),
        ),
    ]
