# Generated by Django 6.0 on 2026-01-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='other_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
