# Generated by Django 6.0 on 2026-07-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_productbuyprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='transporter_name',
            field=models.CharField(blank=True, help_text='Name of the transporter carrying the goods', max_length=100, null=True),
        ),
    ]
