# Generated by Django 6.0 on 2026-09-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_invoice_transporter_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="dispatched_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this invoice's items were sent to the display store via the morning Dispatch List. Blank means it's still pending dispatch.",
                null=True,
            ),
        ),
    ]
