from django.core.management.base import BaseCommand
from django.core.mail import EmailMessage
from django.utils import timezone
from django.conf import settings
from pathlib import Path
import os


class Command(BaseCommand):
    help = 'Send the daily report (generated by export_daily_report) to configured recipients'

    def add_arguments(self, parser):
        parser.add_argument('--date', type=str, help='Date in YYYY-MM-DD (default: today)')
        parser.add_argument('--recipients', type=str, help='Comma-separated recipients (overrides env)')
        parser.add_argument('--generate', action='store_true', help='Generate the report if missing')

    def handle(self, *args, **options):
        target_date = options.get('date')
        if target_date:
            try:
                day = timezone.datetime.strptime(target_date, '%Y-%m-%d').date()
            except Exception:
                self.stderr.write('Invalid date format, expected YYYY-MM-DD')
                return
        else:
            day = timezone.localdate()

        reports_dir = Path(settings.BASE_DIR) / 'reports'
        reports_dir.mkdir(parents=True, exist_ok=True)
        report_path = reports_dir / f'daily_report_{day}.zip'

        if not report_path.exists() and options.get('generate'):
            # Generate report
            from django.core.management import call_command
            call_command('export_daily_report', date=str(day))

        if not report_path.exists():
            self.stderr.write(f'Report not found at {report_path}. Use --generate to create it.')
            return

        recipients = []
        if options.get('recipients'):
            recipients = [e.strip() for e in options['recipients'].split(',') if e.strip()]
        else:
            env_val = os.environ.get('DAILY_REPORT_RECIPIENTS', '')
            recipients = [e.strip() for e in env_val.split(',') if e.strip()]

        if not recipients:
            self.stderr.write('No recipients configured (DAILY_REPORT_RECIPIENTS or --recipients).')
            return

        subject = f"Daily Report {day}"
        body = f"Attached is the daily inventory and sales report for {day}."

        email = EmailMessage(subject, body, settings.DEFAULT_FROM_EMAIL, recipients)
        with open(report_path, 'rb') as f:
            email.attach(report_path.name, f.read(), 'application/zip')
        email.send()
        self.stdout.write(self.style.SUCCESS(f'Email sent to: {", ".join(recipients)}'))

